### ISSUE TITLE
Question on robustness

### ISSUE THREAD

**Issue by tim-cools** [pauldotknopf/JavaScriptViewEngine#14]
Hi,

Just a quick question to ask whether you use this in production? Or plan to?
And did you run benchmarks for it?

Thanks 

Tim

**Comment by jcd79** [comment]
For what it's worth:
I'm using it in a production app. Small scale though, it servers in a web app that delivers some web views to our otherwise native iOS / Android apps. Has been stable and working as expected. It's running on a B1 - Basic Azure web app plan. I have not looked into performance as the amount of users at any given time is to small to give any performance insight.

**Comment by pauldotknopf** [comment]
I have used it in production for a client. He wound up not using it though (business reasons).

I have tested the performance. When rendering a large amount of markup, the result was adding only milliseconds, even under load.

In this solution, there is only one new part (JavaScriptServices, from Microsoft) that you wouldn't have when using node directory (via express or something), which is the additional network request from localhost to localhost (from .NET to node) for the rendered markup.

The only bottleneck that you will (not likely) run into is the fact that .NET can handle more concurrent requests that node can (since node is single-threaded). However, since we are purely rendering markup in node (not async callbacks, or IO), you are unlikely to run into this. In any event, there are ways around this, such as using multiple node.exe's. I don't think this is supported in JavaScriptServices though, but it could be. It probably isn't supported because it probably isn't needed.

I don't see anybody really running into performance issues with this project. However, if there is, I would  take a look at it.

**Comment by tim-cools** [comment]
@pauldotknopf @jcd79 

I use it too in a web-project for rendering Recat, and will put it in production soon. But I had no time to do any real benchmarks yet. Thanks for the feedback!! If I'm able to run some tests I will post the result later...
